# Generated by Django 3.0.8 on 2021-03-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='adddress',
            new_name='address',
        ),
    ]
